--// SPDX-License-Identifier: Unlicense
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(0, 'Pagination preview', 'FineReport', 'Preview', 'page', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(1, 'Online analysis', 'FineReport', 'View', 'view', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(2, 'Fill in the preview', 'FineReport', 'Preview', 'write', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(3, 'Decision report preview', 'FineReport', 'Preview', 'form', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(4, 'line engine', 'FineReport', 'View', 'layer', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(5, 'online editing', 'FineReport', 'Edit', 'edit', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(6, 'new report', 'FineReport', 'Edit', 'write_plus', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(7, 'New engine preview', 'FineReport', 'Preview', 'page_plus', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(8, 'Large screen FVS Preview', 'FineReport', 'Preview', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(9, 'Developer debug Preview', 'FineReport', 'Preview', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(10, 'Excel Paginated Export', 'FineReport', 'Export', 'excel', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(11, 'Export to Excel as is', 'FineReport', 'Export', 'excelO', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(12, 'Excel full page export', 'FineReport', 'Export', 'excelL', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(13, 'Excel pagination and sheet export', 'FineReport', 'Export', 'excelS', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(14, 'PDF export', 'FineReport', 'Export', 'pdf', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(15, 'Word export', 'FineReport', 'Export', 'word', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(16, 'SVG export', 'FineReport', 'Export', 'svg', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(17, 'CSV export', 'FineReport', 'Export', 'csv', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(18, 'Text export', 'FineReport', 'Export', 'text', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(19, 'JPG image export', 'FineReport', 'Export', 'jpg', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(20, 'PNG image export', 'FineReport', 'Export', 'png', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(21, 'GIF image export', 'FineReport', 'Export', 'gif', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(22, 'BMP image export', 'FineReport', 'Export', 'bmp', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(23, 'WBMP image export', 'FineReport', 'Export', 'wbmp', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(24, 'Built-in dataset export templates', 'FineReport', 'Export', 'cpt', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(25, 'HTML export', 'FineReport', 'Export', 'html', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(26, 'Fill out HTML export', 'FineReport', 'Export', 'write_html', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(27, 'BI Export Excel', 'FineReport', 'Export', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(30, 'Flash printing', 'FineReport', 'Print', 'print_flash', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(31, 'PDF printing', 'FineReport', 'Print', 'print_pdf', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(32, 'Applet printing', 'FineReport', 'Print', 'print_applet', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(33, 'Zero client printing', 'FineReport', 'Print', 'print_noclient', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(34, 'local software printing', 'FineReport', 'Print', 'print_native', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(101, 'View BI Templates', 'FineBI', 'View', 'bi_view', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(102, 'Edit BI templates', 'FineBI', 'Edit', 'bi_edit', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(103, 'Share BI templates', 'FineBI', 'Share', 'bi_share', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(104, 'Create BI public link', 'FineBI', 'Share', 'bi_create_publink', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(105, 'View BI public link', 'FineBI', 'View', 'bi_view_share', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(106, 'BI template global export PDF', 'FineBI', 'Export', 'bi_template_export_pdf', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(107, 'BI template global export to Excel', 'FineBI', 'Export', 'bi_template_export_excel', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(108, 'BI component export to Excel', 'FineBI', 'Export', 'bi_component_export_excel', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(109, 'BI template save as', 'FineBI', 'View', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(201, 'Close the browser or tab page (BI)', 'FineBI', 'View', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(202, 'Edit Self-Service Datasets', 'FineBI', 'Edit', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(203, 'Share self-service datasets', 'FineBI', 'Share', 'bi_analysis_table_share', NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(204, 'Close Share Self-Service Datasets', 'FineBI', 'Share', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(205, 'Close Share BI Template', 'FineBI', 'Share', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(206, 'Close BI public link', 'FineBI', 'Share', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(302, 'Edit component', 'FineBI', 'Edit', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(401, 'Preview excel plug-in template', 'FineBI', 'View', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(402, 'Edit excel plug-in template (reserved)', 'FineBI', 'Edit', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(403, 'Share excel plug-in template', 'FineBI', 'Share', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(404, 'Create excel plug-in public link', 'FineBI', 'Share', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(405, 'Access excel plug-in templates through public links', 'FineBI', 'View', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(408, 'Excel component export Excel', 'FineBI', 'Export', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(502, 'Subject editing', 'FineBI', 'Edit', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(503, 'Group collaboration', 'FineBI', 'Share', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(504, 'Subject collaboration', 'FineBI', 'Share', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(602, 'Base table editing', 'FineBI', 'Edit', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(301, 'Component preview', 'FineBI', 'Edit', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(409, 'Save excel dashboard as', 'FineBI', 'Export', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(501, 'Subject viewing', 'FineBI', 'Edit', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(702, 'Analysis Document editing', 'FineBI', 'Edit', NULL, NULL);
INSERT INTO public.z01_dict_fre_op_type (op_code, op_type, module_name, op_cat, op_parameter, coding) VALUES(701, 'View Analysis Document', 'FineBI', 'View', NULL, NULL);